Name:           ros-indigo-flask-reverse-proxy
Version:        0.2.0
Release:        2%{?dist}
Summary:        ROS flask_reverse_proxy package

Group:          Development/Libraries
License:        MIT
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin >= 0.6.18
BuildRequires:  ros-indigo-catkin-pip >= 0.2.0

%description
A Flask &quot;extension&quot; for applications in a reverse proxy not at the
root. A complete rip off of http://flask.pocoo.org/snippets/35/.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Mar 23 2017 AlexV <asmodehn@gmail.com> - 0.2.0-2
- Autogenerated by Bloom

* Thu Nov 17 2016 AlexV <asmodehn@gmail.com> - 0.2.0-1
- Autogenerated by Bloom

* Thu Nov 17 2016 AlexV <asmodehn@gmail.com> - 0.2.0-0
- Autogenerated by Bloom

